import { useState, useEffect, createContext, useContext } from 'react'

const LanguageContext = createContext()

// Translation data - Complete translations from original JavaScript
const translations = {
  en: {
    HOME: 'HOME',
    ABOUT: 'ABOUT', 
    MENU: 'MENU',
    BLOGS: 'BLOGS',
    OUTLETS: 'OUTLETS',
    CONTACT: 'CONTACT',
    'Soft. Crispy. Irresistible.': 'Soft. Crispy. Irresistible.',
    "INDONESIA'S BEST<br>BROWNIES PASTRY": "INDONESIA'S BEST<br>BROWNIES PASTRY",
    'OUR COMPANY': 'OUR COMPANY',
    'TRADITIONAL<br>INDONESIAN FOODS<br>AND HERITAGE': 'TRADITIONAL<br>INDONESIAN FOODS<br>AND HERITAGE',
    'The Heart of Every Kitchen': 'The Heart of Every Kitchen',
    'Restaurants are much more than just places where food is sold—they are hubs of tradition, culture, and creativity.': 'Restaurants are much more than just places where food is sold—they are hubs of tradition, culture, and creativity.',
    'Innovation Meets Tradition': 'Innovation Meets Tradition',
    "Restaurants will continue to evolve, balancing the rich traditions of cooking with the modern consumer's needs.": "Restaurants will continue to evolve, balancing the rich traditions of cooking with the modern consumer's needs.",
    'Learn More About Us': 'Learn More About Us',
    'SPECIALTY DISHES': 'SPECIALTY DISHES',
    'FRESH FROM THE KITCHEN': 'FRESH FROM THE KITCHEN',
    'Experience the perfect fusion of traditional Indonesian flavors with modern culinary techniques, crafted daily with the finest ingredients.': 'Experience the perfect fusion of traditional Indonesian flavors with modern culinary techniques, crafted daily with the finest ingredients.',
    'Traditional Indonesian': 'Traditional Indonesian',
    'Authentic recipes passed down through generations with original spices and cooking methods': 'Authentic recipes passed down through generations with original spices and cooking methods',
    'Modern Presentation': 'Modern Presentation',
    'Contemporary plating and presentation techniques while preserving authentic flavors': 'Contemporary plating and presentation techniques while preserving authentic flavors',
    'Premium Quality': 'Premium Quality',
    'Only the finest local ingredients sourced directly from trusted Indonesian suppliers': 'Only the finest local ingredients sourced directly from trusted Indonesian suppliers',
    'OUR SPECIALTY': 'OUR SPECIALTY',
    'DELICIOUS MENU': 'DELICIOUS MENU',
    'Discover our signature collection of traditional Indonesian brownies and pastries.': 'Discover our signature collection of traditional Indonesian brownies and pastries.',
    'Chocolate Brownies': 'Chocolate Brownies',
    'Rich and fudgy chocolate brownies made with premium cocoa and traditional Indonesian spices. Perfect balance of sweetness and texture.': 'Rich and fudgy chocolate brownies made with premium cocoa and traditional Indonesian spices. Perfect balance of sweetness and texture.',
    'Brownies': 'Brownies',
    'Traditional Pastry': 'Traditional Pastry',
    'Authentic Indonesian pastry with crispy exterior and soft interior. Made with traditional recipes passed down through generations.': 'Authentic Indonesian pastry with crispy exterior and soft interior. Made with traditional recipes passed down through generations.',
    'Pastry': 'Pastry',
    'Premium Cake': 'Premium Cake',
    'Luxurious layered cake with premium ingredients and modern presentation. A perfect fusion of traditional taste and contemporary style.': 'Luxurious layered cake with premium ingredients and modern presentation. A perfect fusion of traditional taste and contemporary style.',
    'Cake': 'Cake',
    'View Full Menu': 'View Full Menu',
    'OUR STORIES': 'OUR STORIES',
    'LATEST FROM BLOG': 'LATEST FROM BLOG',
    'Discover the passion, tradition, and innovation behind every Monyenyo creation': 'Discover the passion, tradition, and innovation behind every Monyenyo creation',
    'Heritage': 'Heritage',
    'The Art of Traditional Indonesian Brownies': 'The Art of Traditional Indonesian Brownies',
    'Journey through generations of baking traditions as we unveil the secrets behind our signature brownies': 'Journey through generations of baking traditions as we unveil the secrets behind our signature brownies',
    'Recipes': 'Recipes',
    'Secrets to Perfect Brownies': 'Secrets to Perfect Brownies',
    'Behind Scenes': 'Behind Scenes',
    'Morning at Monyenyo Kitchen': 'Morning at Monyenyo Kitchen',
    "Indonesia's Spice Heritage": "Indonesia's Spice Heritage",
    'Family Recipe Legacy': 'Family Recipe Legacy',
    'View All Stories': 'View All Stories',
    'A group of highly skilled professionals building a future of shared success.': 'A group of highly skilled professionals building a future of shared success.',
    'Contact Us': 'Contact Us',
    'Social Media': 'Social Media',
    'All Rights Reserved.': 'All Rights Reserved.',
    // Blogs page translations
    'STORIES & INSIGHTS': 'STORIES & INSIGHTS',
    'Discover the passion, tradition, and innovation behind every Monyenyo creation through our collection of stories, recipes, and behind-the-scenes moments.': 'Discover the passion, tradition, and innovation behind every Monyenyo creation through our collection of stories, recipes, and behind-the-scenes moments.',
    'Head Pastry Chef': 'Head Pastry Chef',
    'Read Full Story': 'Read Full Story',
    'EXPLORE BY CATEGORY': 'EXPLORE BY CATEGORY',
    'Find stories that interest you most': 'Find stories that interest you most',
    'All Stories': 'All Stories',
    'Tips': 'Tips',
    'Behind-scenes': 'Behind Scenes',
    'Load More Stories': 'Load More Stories',
    'Stay in the Loop': 'Stay in the Loop',
    'Get our latest stories, recipes, and exclusive offers delivered straight to your inbox.': 'Get our latest stories, recipes, and exclusive offers delivered straight to your inbox.',
    'Enter your email address': 'Enter your email address',
    'Subscribe': 'Subscribe',
    'We respect your privacy. Unsubscribe at any time.': 'We respect your privacy. Unsubscribe at any time.',
    // Blog articles content
    'Master the art of creating the perfect brownie texture with our time-tested techniques and premium ingredient secrets.': 'Master the art of creating the perfect brownie texture with our time-tested techniques and premium ingredient secrets.',
    'by Chef Budi': 'by Chef Budi',
    'Indonesian Spices in Modern Baking': 'Indonesian Spices in Modern Baking',
    'Explore how traditional Indonesian spices like pandan, cinnamon, and nutmeg transform modern pastry creations.': 'Explore how traditional Indonesian spices like pandan, cinnamon, and nutmeg transform modern pastry creations.',
    'by Chef Sari': 'by Chef Sari',
    'A Day in Monyenyo Kitchen': 'A Day in Monyenyo Kitchen',
    'Follow our bakers through their daily routine of creating fresh, delicious pastries from dawn to dusk.': 'Follow our bakers through their daily routine of creating fresh, delicious pastries from dawn to dusk.',
    'by Team Monyenyo': 'by Team Monyenyo',
    'Home Baking Made Simple': 'Home Baking Made Simple',
    'Professional tips and tricks to elevate your home baking game and achieve bakery-quality results.': 'Professional tips and tricks to elevate your home baking game and achieve bakery-quality results.',
    'by Chef Maria': 'by Chef Maria',
    'Traditional Pastry Recipes': 'Traditional Pastry Recipes',
    'Recreate classic Indonesian pastries at home with our authentic family recipes passed down through generations.': 'Recreate classic Indonesian pastries at home with our authentic family recipes passed down through generations.',
    'by Chef Andi': 'by Chef Andi',
    'Preserving Culinary Heritage': 'Preserving Culinary Heritage',
    'Our mission to preserve and celebrate Indonesia\'s rich baking traditions while embracing modern innovation.': 'Our mission to preserve and celebrate Indonesia\'s rich baking traditions while embracing modern innovation.',
    'by Founder': 'by Founder',
    'Journey through generations of baking traditions as we unveil the secrets behind our signature brownies. From ancient spice blending techniques to modern presentation methods, discover how we honor Indonesia\'s rich culinary heritage.': 'Journey through generations of baking traditions as we unveil the secrets behind our signature brownies. From ancient spice blending techniques to modern presentation methods, discover how we honor Indonesia\'s rich culinary heritage.',
    // Outlets page translations
    'Our Store Location': 'Our Store Location',
    'Visit Monyenyo Bandung': 'Visit Monyenyo Bandung',
    'Experience authentic Indonesian brownies in our modern flagship store located in the heart of Bandung': 'Experience authentic Indonesian brownies in our modern flagship store located in the heart of Bandung',
    'Find Our Location': 'Find Our Location',
    // Contact page translations
    'Get in Touch': 'Get in Touch',
    'Contact Us Today': 'Contact Us Today',
    'We\'d love to hear from you. Reach out for inquiries, orders, or collaboration opportunities.': 'We\'d love to hear from you. Reach out for inquiries, orders, or collaboration opportunities.',
    'Send us a Message': 'Send us a Message',
    'Have a question or want to collaborate? We\'re here to help and excited to connect with you.': 'Have a question or want to collaborate? We\'re here to help and excited to connect with you.',
    'Name': 'Name',
    'Email': 'Email',
    'Message': 'Message',
    'Your Name': 'Your Name',
    'you@email.com': 'you@email.com',
    'Type your message...': 'Type your message...',
    'Send Message': 'Send Message',
    'Call Us': 'Call Us',
    'WhatsApp': 'WhatsApp',
    'Message sent successfully!': 'Message sent successfully!',
    'Sorry, there was a problem sending your message. Please try again later.': 'Sorry, there was a problem sending your message. Please try again later.',
    'Get in touch with Monyenyo. Contact us for inquiries, orders, or collaboration opportunities.': 'Get in touch with Monyenyo. Contact us for inquiries, orders, or collaboration opportunities.',
    // Home page translations
    "Monyenyo - Indonesia's Best Brownies Pastry": "Monyenyo - Indonesia's Best Brownies Pastry",
    "Experience the perfect fusion of traditional Indonesian flavors with modern culinary techniques. Discover Monyenyo's signature brownies and pastries.": "Experience the perfect fusion of traditional Indonesian flavors with modern culinary techniques. Discover Monyenyo's signature brownies and pastries.",
    "Indonesian brownies, traditional pastry, Monyenyo, Jakarta food, Indonesian desserts": "Indonesian brownies, traditional pastry, Monyenyo, Jakarta food, Indonesian desserts",
    'FEATURED': 'FEATURED'
  },
  id: {
    HOME: 'BERANDA',
    ABOUT: 'TENTANG',
    MENU: 'MENU',
    BLOGS: 'BLOG',
    OUTLETS: 'OUTLET',
    CONTACT: 'KONTAK',
    'Soft. Crispy. Irresistible.': 'Lembut. Renyah. Tak Tertahankan.',
    "INDONESIA'S BEST<br>BROWNIES PASTRY": "BROWNIES PASTRY<br>TERBAIK DI INDONESIA",
    'OUR COMPANY': 'TENTANG KAMI',
    'TRADITIONAL<br>INDONESIAN FOODS<br>AND HERITAGE': 'MAKANAN TRADISIONAL<br>INDONESIA & WARISAN',
    'The Heart of Every Kitchen': 'Jantung Setiap Dapur',
    'Restaurants are much more than just places where food is sold—they are hubs of tradition, culture, and creativity.': 'Restoran bukan sekadar tempat makan—mereka adalah pusat tradisi, budaya, dan kreativitas.',
    'Innovation Meets Tradition': 'Inovasi Bertemu Tradisi',
    "Restaurants will continue to evolve, balancing the rich traditions of cooking with the modern consumer's needs.": "Restoran akan terus berkembang, menyeimbangkan tradisi memasak dengan kebutuhan konsumen modern.",
    'Learn More About Us': 'Selengkapnya Tentang Kami',
    'SPECIALTY DISHES': 'MENU SPESIAL',
    'FRESH FROM THE KITCHEN': 'SEGAR DARI DAPUR',
    'Experience the perfect fusion of traditional Indonesian flavors with modern culinary techniques, crafted daily with the finest ingredients.': 'Rasakan perpaduan sempurna cita rasa tradisional Indonesia dengan teknik kuliner modern, dibuat setiap hari dengan bahan terbaik.',
    'Traditional Indonesian': 'Masakan Tradisional',
    'Authentic recipes passed down through generations with original spices and cooking methods': 'Resep otentik turun-temurun dengan rempah dan teknik asli',
    'Modern Presentation': 'Presentasi Modern',
    'Contemporary plating and presentation techniques while preserving authentic flavors': 'Teknik plating dan presentasi modern tanpa menghilangkan cita rasa asli',
    'Premium Quality': 'Kualitas Premium',
    'Only the finest local ingredients sourced directly from trusted Indonesian suppliers': 'Hanya bahan lokal terbaik langsung dari pemasok terpercaya',
    'OUR SPECIALTY': 'SPESIAL KAMI',
    'DELICIOUS MENU': 'MENU LEZAT',
    'Discover our signature collection of traditional Indonesian brownies and pastries.': 'Temukan koleksi signature brownies dan pastry tradisional Indonesia kami.',
    'Chocolate Brownies': 'Brownies Cokelat',
    'Rich and fudgy chocolate brownies made with premium cocoa and traditional Indonesian spices. Perfect balance of sweetness and texture.': 'Brownies cokelat legit dengan kakao premium dan rempah tradisional. Manis dan tekstur seimbang.',
    'Brownies': 'Brownies',
    'Traditional Pastry': 'Pastry Tradisional',
    'Authentic Indonesian pastry with crispy exterior and soft interior. Made with traditional recipes passed down through generations.': 'Pastry Indonesia otentik, luar renyah dalam lembut. Resep turun-temurun.',
    'Pastry': 'Pastry',
    'Premium Cake': 'Kue Premium',
    'Luxurious layered cake with premium ingredients and modern presentation. A perfect fusion of traditional taste and contemporary style.': 'Kue lapis mewah dengan bahan premium dan tampilan modern. Perpaduan tradisi dan gaya kontemporer.',
    'Cake': 'Kue',
    'View Full Menu': 'Lihat Menu Lengkap',
    'OUR STORIES': 'CERITA KAMI',
    'LATEST FROM BLOG': 'TERBARU DARI BLOG',
    'Discover the passion, tradition, and innovation behind every Monyenyo creation': 'Temukan semangat, tradisi, dan inovasi di balik setiap kreasi Monyenyo',
    'Heritage': 'Warisan',
    'The Art of Traditional Indonesian Brownies': 'Seni Brownies Tradisional Indonesia',
    'Journey through generations of baking traditions as we unveil the secrets behind our signature brownies': 'Jelajahi tradisi memanggang turun-temurun saat kami mengungkap rahasia di balik brownies andalan kami',
    'Recipes': 'Resep',
    'Secrets to Perfect Brownies': 'Rahasia Brownies Sempurna',
    'Behind Scenes': 'Di Balik Layar',
    'Morning at Monyenyo Kitchen': 'Pagi di Dapur Monyenyo',
    "Indonesia's Spice Heritage": "Warisan Rempah Indonesia",
    'Family Recipe Legacy': 'Warisan Resep Keluarga',
    'View All Stories': 'Lihat Semua Cerita',
    'A group of highly skilled professionals building a future of shared success.': 'Tim profesional membangun masa depan bersama.',
    'Contact Us': 'Hubungi Kami',
    'Social Media': 'Media Sosial',
    'All Rights Reserved.': 'Hak Cipta Dilindungi.',
    // Blogs page translations
    'STORIES & INSIGHTS': 'CERITA & WAWASAN',
    'Discover the passion, tradition, and innovation behind every Monyenyo creation through our collection of stories, recipes, and behind-the-scenes moments.': 'Temukan semangat, tradisi, dan inovasi di balik setiap kreasi Monyenyo melalui koleksi cerita, resep, dan momen di balik layar kami.',
    'Head Pastry Chef': 'Kepala Chef Pastry',
    'Read Full Story': 'Baca Cerita Lengkap',
    'EXPLORE BY CATEGORY': 'JELAJAHI BERDASARKAN KATEGORI',
    'Find stories that interest you most': 'Temukan cerita yang paling menarik bagi Anda',
    'All Stories': 'Semua Cerita',
    'Tips': 'Tips',
    'Behind-scenes': 'Di Balik Layar',
    'Load More Stories': 'Muat Lebih Banyak Cerita',
    'Stay in the Loop': 'Tetap Terhubung',
    'Get our latest stories, recipes, and exclusive offers delivered straight to your inbox.': 'Dapatkan cerita terbaru, resep, dan penawaran eksklusif langsung ke kotak masuk Anda.',
    'Enter your email address': 'Masukkan alamat email Anda',
    'Subscribe': 'Berlangganan',
    'We respect your privacy. Unsubscribe at any time.': 'Kami menghormati privasi Anda. Berhenti berlangganan kapan saja.',
    // Blog articles content
    'Master the art of creating the perfect brownie texture with our time-tested techniques and premium ingredient secrets.': 'Kuasai seni menciptakan tekstur brownies sempurna dengan teknik yang telah terbukti dan rahasia bahan premium kami.',
    'by Chef Budi': 'oleh Chef Budi',
    'Indonesian Spices in Modern Baking': 'Rempah Indonesia dalam Kue Modern',
    'Explore how traditional Indonesian spices like pandan, cinnamon, and nutmeg transform modern pastry creations.': 'Jelajahi bagaimana rempah tradisional Indonesia seperti pandan, kayu manis, dan pala mengubah kreasi pastry modern.',
    'by Chef Sari': 'oleh Chef Sari',
    'A Day in Monyenyo Kitchen': 'Sehari di Dapur Monyenyo',
    'Follow our bakers through their daily routine of creating fresh, delicious pastries from dawn to dusk.': 'Ikuti para baker kami melalui rutinitas harian mereka menciptakan pastry segar dan lezat dari fajar hingga senja.',
    'by Team Monyenyo': 'oleh Tim Monyenyo',
    'Home Baking Made Simple': 'Memanggang di Rumah Jadi Mudah',
    'Professional tips and tricks to elevate your home baking game and achieve bakery-quality results.': 'Tips dan trik profesional untuk meningkatkan kemampuan memanggang di rumah dan mencapai hasil berkualitas toko kue.',
    'by Chef Maria': 'oleh Chef Maria',
    'Traditional Pastry Recipes': 'Resep Pastry Tradisional',
    'Recreate classic Indonesian pastries at home with our authentic family recipes passed down through generations.': 'Buat ulang pastry Indonesia klasik di rumah dengan resep keluarga otentik kami yang diwariskan turun-temurun.',
    'by Chef Andi': 'oleh Chef Andi',
    'Preserving Culinary Heritage': 'Melestarikan Warisan Kuliner',
    'Our mission to preserve and celebrate Indonesia\'s rich baking traditions while embracing modern innovation.': 'Misi kami untuk melestarikan dan merayakan tradisi memanggang kaya Indonesia sambil merangkul inovasi modern.',
    'by Founder': 'oleh Pendiri',
    'Journey through generations of baking traditions as we unveil the secrets behind our signature brownies. From ancient spice blending techniques to modern presentation methods, discover how we honor Indonesia\'s rich culinary heritage.': 'Perjalanan melalui generasi tradisi memanggang saat kami mengungkap rahasia di balik brownies andalan kami. Dari teknik pencampuran rempah kuno hingga metode presentasi modern, temukan bagaimana kami menghormati warisan kuliner kaya Indonesia.',
    // Outlets page translations
    'Our Store Location': 'Lokasi Toko Kami',
    'Visit Monyenyo Bandung': 'Kunjungi Monyenyo Bandung',
    'Experience authentic Indonesian brownies in our modern flagship store located in the heart of Bandung': 'Rasakan brownies Indonesia otentik di toko flagship modern kami yang terletak di jantung Bandung',
    'Find Our Location': 'Temukan Lokasi Kami',
    // Contact page translations
    'Get in Touch': 'Hubungi Kami',
    'Contact Us Today': 'Hubungi Kami Hari Ini',
    'We\'d love to hear from you. Reach out for inquiries, orders, or collaboration opportunities.': 'Kami ingin mendengar dari Anda. Hubungi kami untuk pertanyaan, pesanan, atau peluang kolaborasi.',
    'Send us a Message': 'Kirim Pesan',
    'Have a question or want to collaborate? We\'re here to help and excited to connect with you.': 'Punya pertanyaan atau ingin berkolaborasi? Kami di sini untuk membantu dan senang terhubung dengan Anda.',
    'Name': 'Nama',
    'Email': 'Email',
    'Message': 'Pesan',
    'Your Name': 'Nama Anda',
    'you@email.com': 'anda@email.com',
    'Type your message...': 'Ketik pesan Anda...',
    'Send Message': 'Kirim Pesan',
    'Call Us': 'Telepon Kami',
    'WhatsApp': 'WhatsApp',
    'Message sent successfully!': 'Pesan berhasil dikirim!',
    'Sorry, there was a problem sending your message. Please try again later.': 'Maaf, terjadi masalah saat mengirim pesan Anda. Silakan coba lagi nanti.',
    'Get in touch with Monyenyo. Contact us for inquiries, orders, or collaboration opportunities.': 'Hubungi Monyenyo. Kontak kami untuk pertanyaan, pesanan, atau peluang kolaborasi.',
    // Home page translations
    "Monyenyo - Indonesia's Best Brownies Pastry": "Monyenyo - Brownies Pastry Terbaik Indonesia",
    "Experience the perfect fusion of traditional Indonesian flavors with modern culinary techniques. Discover Monyenyo's signature brownies and pastries.": "Rasakan perpaduan sempurna cita rasa tradisional Indonesia dengan teknik kuliner modern. Temukan brownies dan pastry khas Monyenyo.",
    "Indonesian brownies, traditional pastry, Monyenyo, Jakarta food, Indonesian desserts": "brownies Indonesia, pastry tradisional, Monyenyo, makanan Jakarta, dessert Indonesia",
    'FEATURED': 'UNGGULAN'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('monyenyo_lang') || 'en'
  })

  useEffect(() => {
    localStorage.setItem('monyenyo_lang', language)
  }, [language])

  const t = (key) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}